import { StatsData } from '../components/StatsStore.js';
import { Configuration } from '../types/config.js';

export function generateDashboardHTML(stats: StatsData, config: Configuration): string {
  const encryptCacheOn = config.security?.encryptCache !== false;
  const autoGeneratedSecret = !process.env.RELAY_CACHE_SECRET;

  const hitRate = stats.lifetime.totalRequestsProxied > 0 
    ? ((stats.lifetime.totalExactCacheHits + stats.lifetime.totalFuzzyCacheHits) / stats.lifetime.totalRequestsProxied * 100).toFixed(1)
    : '0.0';

  let providerHtml = '';
  for (const [providerId, pStats] of Object.entries(stats.providers)) {
    providerHtml += `
      <div class="glass-card rounded-xl p-5 shadow-sm hover:border-slate-600 transition-colors">
        <h3 class="text-base font-semibold tracking-tight mb-4 flex items-center"><i data-lucide="server" class="w-4 h-4 mr-2 text-mutedForeground"></i>${providerId}</h3>
        <div class="space-y-2 text-sm">
          <div class="flex justify-between items-center pb-2 border-b border-border/50">
            <span class="text-mutedForeground">Requests</span>
            <span class="font-medium">${pStats.requestsProxied}</span>
          </div>
          <div class="flex justify-between items-center pb-2 border-b border-border/50">
            <span class="text-mutedForeground">Exact Hits</span>
            <span class="font-medium">${pStats.exactCacheHits}</span>
          </div>
          <div class="flex justify-between items-center pb-2 border-b border-border/50">
            <span class="text-mutedForeground">Fuzzy Hits</span>
            <span class="font-medium">${pStats.fuzzyCacheHits}</span>
          </div>
          <div class="flex justify-between items-center pb-2 border-b border-border/50">
            <span class="text-mutedForeground">Dedups</span>
            <span class="font-medium">${pStats.dedupRequests}</span>
          </div>
          <div class="flex justify-between items-center pt-1">
            <span class="text-mutedForeground">Saved</span>
            <span class="font-semibold text-emerald-500">$${pStats.dollarsSaved.toFixed(4)}</span>
          </div>
        </div>
      </div>
    `;
  }

  // Prepare Chart.js data
  let chartLabels: string[] = [];
  let chartData: number[] = [];
  
  if (Object.keys(stats.dailyRollups).length > 0) {
    const dates = new Set<string>();
    for (const pStats of Object.values(stats.dailyRollups)) {
      for (const date of Object.keys(pStats)) dates.add(date);
    }
    const sortedDates = Array.from(dates).sort();
    
    chartLabels = sortedDates.map(d => d.substring(5)); // MM-DD
    chartData = sortedDates.map(date => {
      let totalCost = 0;
      for (const providerId of Object.keys(stats.dailyRollups)) {
        if (stats.dailyRollups[providerId][date]) {
          totalCost += stats.dailyRollups[providerId][date].cost;
        }
      }
      return parseFloat(totalCost.toFixed(4));
    });
  }

  return `
<!DOCTYPE html>
<html lang="en" class="dark">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Relay Dashboard</title>
  <script src="https://cdn.tailwindcss.com"></script>
  <script src="https://unpkg.com/lucide@latest"></script>
  <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
  <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&display=swap" rel="stylesheet">
  <script>
    tailwind.config = {
      darkMode: 'class',
      theme: {
        extend: {
          fontFamily: { sans: ['Inter', 'sans-serif'] },
          colors: {
            background: 'hsl(222.2 84% 4.9%)',
            foreground: 'hsl(210 40% 98%)',
            card: 'hsl(222.2 84% 4.9%)',
            cardForeground: 'hsl(210 40% 98%)',
            border: 'hsl(217.2 32.6% 17.5%)',
            muted: 'hsl(217.2 32.6% 17.5%)',
            mutedForeground: 'hsl(215 20.2% 65.1%)',
            primary: 'hsl(210 40% 98%)',
            primaryForeground: 'hsl(222.2 47.4% 11.2%)',
          }
        }
      }
    }
  </script>
  <style>
    body { background-color: theme('colors.background'); color: theme('colors.foreground'); }
    .lucide { width: 1.25rem; height: 1.25rem; }
    .glass-card {
      background: rgba(15, 23, 42, 0.4);
      backdrop-filter: blur(12px);
      -webkit-backdrop-filter: blur(12px);
      border: 1px solid theme('colors.border');
    }
    
    .chart-container {
      display: flex;
      align-items: flex-end;
      height: 150px;
      gap: 6px;
      padding-top: 1rem;
    }
    .bar-wrapper {
      flex: 1;
      display: flex;
      flex-direction: column;
      align-items: center;
      justify-content: flex-end;
      height: 100%;
      position: relative;
    }
    .bar {
      width: 100%;
      background: theme('colors.primary');
      border-radius: 4px 4px 0 0;
      transition: all 0.3s ease;
      opacity: 0.8;
    }
    .bar:hover { opacity: 1; filter: brightness(1.2); }
    .bar-label {
      font-size: 0.65rem;
      color: theme('colors.mutedForeground');
      margin-top: 6px;
      transform: rotate(-45deg);
      white-space: nowrap;
    }
    .tooltip {
      visibility: hidden;
      position: absolute;
      bottom: calc(100% + 5px);
      background: theme('colors.primary');
      color: theme('colors.primaryForeground');
      padding: 4px 8px;
      border-radius: 4px;
      font-size: 0.75rem;
      font-weight: 500;
      white-space: nowrap;
      opacity: 0;
      transition: all 0.2s ease;
      z-index: 10;
    }
    .bar-wrapper:hover .tooltip {
      visibility: visible;
      opacity: 1;
      transform: translateY(-5px);
    }
  </style>
</head>
<body class="min-h-screen p-6 md:p-12 font-sans antialiased">
  <div class="max-w-6xl mx-auto space-y-8">
    
    <!-- Header -->
    <div class="flex items-center justify-between border-b border-border pb-6">
      <div class="flex items-center space-x-3">
        <div class="p-2 bg-primary text-primaryForeground rounded-lg shadow-sm">
          <i data-lucide="zap"></i>
        </div>
        <div>
          <h1 class="text-3xl font-bold tracking-tight">Relay Dashboard</h1>
          <p class="text-mutedForeground text-sm mt-1">Real-time LLM caching & proxy analytics</p>
        </div>
      </div>
      <div class="flex items-center space-x-2 text-sm text-mutedForeground">
        <i data-lucide="shield-check" class="text-emerald-500 w-4 h-4"></i>
        <span>Secure Aggregation Mode</span>
      </div>
    </div>

    <!-- Overview Cards -->
    <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
      <div class="glass-card rounded-xl p-6 shadow-sm hover:border-slate-600 transition-colors">
        <div class="flex items-center justify-between">
          <h3 class="text-sm font-medium text-mutedForeground tracking-tight">Total Saved</h3>
          <i data-lucide="dollar-sign" class="text-emerald-500"></i>
        </div>
        <div class="mt-4">
          <span class="text-4xl font-bold">$${stats.lifetime.totalDollarsSaved.toFixed(2)}</span>
        </div>
      </div>
      
      <div class="glass-card rounded-xl p-6 shadow-sm hover:border-slate-600 transition-colors">
        <div class="flex items-center justify-between">
          <h3 class="text-sm font-medium text-mutedForeground tracking-tight">Requests Proxied</h3>
          <i data-lucide="activity" class="text-blue-500"></i>
        </div>
        <div class="mt-4">
          <span class="text-4xl font-bold">${stats.lifetime.totalRequestsProxied}</span>
        </div>
        <p class="text-xs text-mutedForeground mt-2">
          ${stats.lifetime.streamingRequests} streaming / ${stats.lifetime.nonStreamingRequests} standard
        </p>
      </div>

      <div class="glass-card rounded-xl p-6 shadow-sm hover:border-slate-600 transition-colors">
        <div class="flex items-center justify-between">
          <h3 class="text-sm font-medium text-mutedForeground tracking-tight">Hit Rate</h3>
          <i data-lucide="target" class="text-indigo-500"></i>
        </div>
        <div class="mt-4">
          <span class="text-4xl font-bold">${hitRate}%</span>
        </div>
        <p class="text-xs text-mutedForeground mt-2">
          ${stats.lifetime.totalExactCacheHits} exact / ${stats.lifetime.totalFuzzyCacheHits} fuzzy
        </p>
      </div>

      <div class="glass-card rounded-xl p-6 shadow-sm hover:border-slate-600 transition-colors">
        <div class="flex items-center justify-between">
          <h3 class="text-sm font-medium text-mutedForeground tracking-tight">Deduplicated</h3>
          <i data-lucide="layers" class="text-amber-500"></i>
        </div>
        <div class="mt-4">
          <span class="text-4xl font-bold">${stats.lifetime.totalDedupRequests}</span>
        </div>
      </div>
    </div>

    <!-- Chart -->
    <div class="glass-card rounded-xl p-6 shadow-sm">
      <div class="flex items-center justify-between mb-4">
        <div>
          <h2 class="text-lg font-semibold tracking-tight">30-Day Activity</h2>
          <p class="text-sm text-mutedForeground">Rolling daily cost saved across all providers ($)</p>
        </div>
        <i data-lucide="bar-chart-3" class="text-mutedForeground"></i>
      </div>
      <div class="relative h-64 w-full">
        ${chartLabels.length > 0 ? '<canvas id="costChart"></canvas>' : '<div class="absolute inset-0 flex items-center justify-center text-sm text-mutedForeground border border-dashed border-border rounded-lg">No daily data available yet.</div>'}
      </div>
    </div>

    <!-- Provider Breakdown -->
    <div>
      <h2 class="text-lg font-semibold tracking-tight mb-4">Provider Breakdown</h2>
      <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
        ${providerHtml || '<div class="col-span-full text-mutedForeground text-sm p-4 border border-border border-dashed rounded-lg text-center">No provider data yet.</div>'}
      </div>
    </div>

    <!-- Security Status -->
    <div class="glass-card rounded-xl p-6 shadow-sm">
      <div class="flex items-center space-x-2 mb-4">
        <i data-lucide="shield" class="text-mutedForeground"></i>
        <h2 class="text-lg font-semibold tracking-tight">Security & Encryption</h2>
      </div>
      <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
        <div class="flex items-center justify-between p-4 rounded-lg bg-black/20 border border-border/50">
          <span class="text-sm font-medium text-mutedForeground">Cache Encryption (AES-256-GCM)</span>
          ${encryptCacheOn 
            ? '<span class="px-2.5 py-0.5 rounded-full text-xs font-semibold bg-emerald-500/20 text-emerald-400">ENABLED</span>' 
            : '<span class="px-2.5 py-0.5 rounded-full text-xs font-semibold bg-amber-500/20 text-amber-400">DISABLED</span>'}
        </div>
        <div class="flex items-center justify-between p-4 rounded-lg bg-black/20 border border-border/50">
          <span class="text-sm font-medium text-mutedForeground">Cache Secret Material</span>
          ${autoGeneratedSecret 
            ? '<span class="px-2.5 py-0.5 rounded-full text-xs font-semibold bg-indigo-500/20 text-indigo-400 border border-indigo-500/30">AUTO-GENERATED</span>' 
            : '<span class="px-2.5 py-0.5 rounded-full text-xs font-semibold bg-emerald-500/20 text-emerald-400">EXPLICITLY SET</span>'}
        </div>
      </div>
      <p class="text-xs text-mutedForeground mt-4 flex items-start">
        <i data-lucide="info" class="w-4 h-4 mr-1.5 flex-shrink-0"></i>
        The dashboard strictly aggregates numerical statistics. Raw prompts, responses, or API keys are never logged or exposed.
      </p>
    </div>

  </div>
  
  <script>
    // Initialize Lucide icons
    lucide.createIcons();

    // Initialize Chart.js if data exists
    const chartLabels = ${JSON.stringify(chartLabels)};
    const chartData = ${JSON.stringify(chartData)};
    
    if (chartLabels.length > 0) {
      const ctx = document.getElementById('costChart').getContext('2d');
      
      Chart.defaults.color = 'hsl(215, 20.2%, 65.1%)';
      Chart.defaults.font.family = 'Inter, sans-serif';

      new Chart(ctx, {
        type: 'line',
        data: {
          labels: chartLabels,
          datasets: [{
            label: 'Cost Saved ($)',
            data: chartData,
            borderColor: 'hsl(210, 40%, 98%)',
            backgroundColor: 'rgba(56, 189, 248, 0.1)', // Primary tint
            borderWidth: 2,
            pointBackgroundColor: 'hsl(210, 40%, 98%)',
            pointBorderColor: 'transparent',
            pointRadius: 3,
            pointHoverRadius: 5,
            fill: true,
            tension: 0.4
          }]
        },
        options: {
          responsive: true,
          maintainAspectRatio: false,
          plugins: {
            legend: { display: false },
            tooltip: {
              backgroundColor: 'hsl(222.2, 47.4%, 11.2%)', // primaryForeground
              titleColor: 'hsl(210, 40%, 98%)', // primary
              bodyColor: 'hsl(210, 40%, 98%)',
              padding: 10,
              cornerRadius: 6,
              displayColors: false,
              callbacks: {
                label: function(context) {
                  return '$' + context.parsed.y.toFixed(4);
                }
              }
            }
          },
          scales: {
            x: {
              grid: { color: 'rgba(255,255,255,0.05)' },
              ticks: { maxTicksLimit: 10 }
            },
            y: {
              beginAtZero: true,
              grid: { color: 'rgba(255,255,255,0.05)' },
              ticks: {
                callback: function(value) { return '$' + value; }
              }
            }
          }
        }
      });
    }
  </script>
</body>
</html>
  `;
}
