import { StatsData } from '../components/StatsStore.js';
import { Configuration } from '../types/config.js';
// @ts-ignore
import dashboardHtml from './dashboard.html';

export function generateDashboardHTML(stats: StatsData, config: Configuration): string {
  const autoGeneratedSecret = !process.env.RELAY_CACHE_SECRET;

  const configView = {
    security: {
      encryptCache: config.security?.encryptCache !== false
    },
    _metadata: {
      autoGeneratedSecret
    }
  };

  // Inject variables client-side by replacing placeholders
  return (dashboardHtml as string)
    .replace('/*STATS_DATA_PLACEHOLDER*/ {}', JSON.stringify(stats))
    .replace('/*CONFIG_DATA_PLACEHOLDER*/ {}', JSON.stringify(configView));
}
