import { describe, it, expect } from 'vitest';
import { generateDashboardHTML } from '../../src/utils/dashboard.js';
import type { StatsData } from '../../src/components/StatsStore.js';
import type { Configuration } from '../../src/types/config.js';

describe('Dashboard Security Regression', () => {
  it('does not leak sensitive API keys or credentials in the generated dashboard HTML', () => {
    const fakeSecretProviderKey = 'super-secret-provider-api-key-12345';
    const fakeSecretAdminKey = 'super-secret-admin-api-key-67890';
    const fakeSecretBaseUrl = 'https://user:password-secret-abc@api.openai.com';
    
    const stats: StatsData = {
      lifetime: {
        totalRequestsProxied: 10,
        totalExactCacheHits: 4,
        totalFuzzyCacheHits: 1,
        totalCacheMisses: 5,
        totalDedupRequests: 2,
        totalDollarsSaved: 0.15,
        streamingRequests: 8,
        nonStreamingRequests: 2
      },
      providers: {},
      dailyRollups: {}
    };

    const config: Configuration = {
      server: {
        port: 8080,
        host: '0.0.0.0',
        maxConcurrentRequests: 100,
        requestTimeoutMs: 5000
      },
      provider: {
        type: 'openai',
        apiKey: fakeSecretProviderKey,
        baseUrl: fakeSecretBaseUrl
      },
      security: {
        apiKey: fakeSecretAdminKey,
        encryptCache: true
      },
      cache: {
        maxEntries: 1000,
        ttlHours: 24
      },
      fuzzyCache: {
        enabled: false,
        maxTokenEditDistance: 3,
        maxEntries: 100,
        rapidEditWindowMs: 5000,
        rapidEditThreshold: 3
      },
      tokens: {
        budgetPerUserPerDay: 100000,
        warningThresholdPercent: 90
      },
      logging: {
        level: 'info',
        prettyPrint: true
      }
    };

    const html = generateDashboardHTML(stats, config);

    // Assert that the generated HTML does NOT contain any of the secrets
    expect(html).not.toContain(fakeSecretProviderKey);
    expect(html).not.toContain(fakeSecretAdminKey);
    expect(html).not.toContain(fakeSecretBaseUrl);
    expect(html).not.toContain('password-secret');
    
    // Assert that standard allowlisted metadata IS present
    expect(html).toContain('encryptCache');
    expect(html).toContain('autoGeneratedSecret');
  });
});
